version: '3'
  
services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/dev/Dockerfile
    container_name: "NoiseList_backend_dev"
    env_file:
      - ./backend/docker/dev/.env
    volumes:
      - ./backend:/backend
      - ./backend/data:/backend/data
    ports:
      - "7000:7000"
    command: sh /entrypoint.sh
  
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/dev/Dockerfile
    container_name: "NoiseList_frontend_dev"
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - "8080:8080"
    command: npm run serve
