version: '3'
  
services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/prod/Dockerfile
    container_name: "NoiseList_backend"
    env_file:
      - ./backend/docker/prod/.env
    volumes:
      - ./backend/data:/backend/data
    expose:
      - 7000
    command: sh /entrypoint.sh
  
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/prod/Dockerfile
    container_name: "NoiseList_frontend"
    ports:
      - "80:8080"
