version: '3'
  
services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/prod/Dockerfile
    container_name: "NoiseList_backend"
    env_file:
      - ./backend/docker/prod/.env
    volumes:
      - ./backend/data:/backend/data
    expose:
      - 7001
    command: sh /entrypoint.sh
    
  nginx-backend:
    build: backend/docker/prod/nginx/
    ports:
      - "7000:7000"
    depends_on:
      - backend
      
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/prod/Dockerfile
    container_name: "NoiseList_frontend"
    ports:
      - "80:8080"
