# Generated by Django 3.0.8 on 2020-07-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='instruments',
            field=models.ManyToManyField(blank=True, related_name='musics', to='instruments.Instrument'),
        ),
    ]
