# Generated by Django 3.0.8 on 2020-07-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('musics', '0002_music_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='musics', to='tags.Tag'),
        ),
    ]
