# Generated by Django 3.0.8 on 2020-07-25 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('musics', '0003_music_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musics', to='languages.Language'),
        ),
    ]
