# Generated by Django 3.0.8 on 2020-08-04 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('musics', '0004_music_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artist',
        ),
        migrations.AddField(
            model_name='music',
            name='artist_tmp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='artists.Artist'),
            preserve_default=False,
        ),
    ]
