# Generated by Django 3.0.8 on 2020-08-04 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_auto_20200803_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='artist_tmp',
            new_name='artist',
        ),
    ]
