# Generated by Django 3.0.8 on 2020-09-09 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
        ('musics', '0006_auto_20200803_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musics', to='styles.Style'),
        ),
    ]
