# Generated by Django 3.0.8 on 2020-07-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
