# Generated by Django 3.0.8 on 2020-07-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='lightblue', max_length=20),
        ),
    ]
